baseURL = 'https://juliamarch.cleverapps.io'
languageCode = 'fr'
title = 'Julia March'
theme = "cupper-hugo-theme"
MetaDataFormat = "toml"
sectionPagesMenu = "main"

enableGitInfo = true

[taxonomies]
tag = "technocritique"

[permalinks]
post = "/:filename/"

[imaging]
quality = 99

[params]
description = "Site de test conçu avec [Hugo](https://gohugo.io) et le sypathique thème [Cupper](https://github.com/ThePacielloGroup/cupper) project."
homeMetaContent = "Site de test conçu avec Hugo et le sypathique thème Cupper."
footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/)."
dateFormat = "Jan 2, 2006"
codePenUser = "Julia"
katex = true
hideHeaderLinks = false
search = true
showThemeSwitcher = true
defaultDarkTheme = false
moveFooterToHeader = false
logoAlt = "An alternative text description of the logo"
customCss = [ "css/custom_01.css", "css/custom_02.css" ]
customJs = [ "js/custom_01.js", "js/custom_02.js" ]

[[menu.nav]]
name = "Accueil"
url = "/"
weight = 1

[[menu.nav]]
name = "Journal de bord"
url = "/Chronique/"
weight = 2

[[menu.nav]]
name = "À propos"
url = "/about/"
weight = 3

[[menu.nav]]
name = "Technocritique"
url = "/technocritique/"
weight = 4

[[menu.nav]]
name = "RSS"
url = "/index.xml"
weight = 5

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.parser]
attribute = true
autoHeadingID = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false

  [markup.highlight]
  codeFences = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4

  [markup.tableOfContents]
  endLevel = 6
  startLevel = 2