baseURL: https://juliamarch.cleverapps.io
languageCode: fr-eu
defaultContentLanguage: fr
title: Julia March
theme: cupper-hugo-theme
disqusShortname: Julia
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Site de test conçu avec [Hugo](https://gohugo.io) et le sympathique thème extrait du [Cupper](https://github.com/ThePacielloGroup/cupper) project."
  homeMetaContent: Site de test conçu avec Hugo et le sypathique thème [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme).
  homeMetaContent: An accessibility-friendly Hugo theme, ported from the original Cupper project.
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed on [Clever Cloud](https://clever-cloud.com/).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  defaultDarkTheme: true<
  moveFooterToHeader: false
  # navTitleText: Cupper Theme
  logoAlt: An alternative text description of the logo
  customCss:
    - css/custom_01.css
    - css/custom_02.css
  customJs:
    - js/custom_01.js
    - js/custom_02.js
  utterances:
    repo: username/username.github.io
    issueTerm: title
    theme: github-light

menu:
  nav:
    - name: Accueil
      url: /
      weight: 1
    - name: Journal de bord
      url: /note/
      weight: 2
    - name: Technocritique
      url: /technocritique/
      weight: 3
    - name: À propos
      url: /a-propos/
      weight: 4
    - name: RSS
      url: /index.xml
      weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
